### ISSUE TITLE
problem with list

### ISSUE THREAD

**Issue by muzyk10** [mkhon/zfs-vm#2]
I got it working on python 2.7 :)
I've two machines (with different zfs datasests). On one of them "vm.py list" works as expected but on the other i doesn't - the output:
`backup zfs-vm # ./vm.py list
Traceback (most recent call last):
  File "./vm.py", line 931, in <module>
    main(sys.argv)
  File "./vm.py", line 928, in main
    do_fun(args[1:])
  File "./vm.py", line 543, in cmd_list
    filesystems = FS.list(None if len(args) < 1 else args[0])
  File "./vm.py", line 251, in list
    fs = filesystems[fsname]
KeyError: 'rpool/DATA/kvm/mail/data'
`
and the strace:
`read(4, "/packages@auto_daily-2016-07-03-"..., 10473) = 10473
fstat(4, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
lseek(4, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
read(4, "6-09-15-2132\tguid\t10462043519166"..., 11782) = 11782
fstat(4, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
lseek(4, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
read(4, "TOO/portage@auto_daily-2016-07-2"..., 13255) = 13255
fstat(4, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
lseek(4, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
read(4, "\nrpool/ROOT/gentoo@auto_daily-20"..., 14911) = 11825
read(4, "73313714281\nrpool/ROOT/gentoo@au"..., 3086) = 3086
fstat(4, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
lseek(4, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
read(4, "rpool/ROOT/gentoo@auto_daily-201"..., 16775) = 328
read(4, "", 16447)                      = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=25594, si_uid=0, si_status=0, si_utime=38, si_stime=371} ---
close(4)                                = 0
wait4(25594, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 25594
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3985615000
brk(0x790000)                           = 0x790000
write(2, "Traceback (most recent call last"..., 35Traceback (most recent call last):
) = 35
write(2, "  File \"./vm.py\", line 931, in <"..., 40  File "./vm.py", line 931, in <module>
) = 40
open("./vm.py", O_RDONLY)               = 4
fstat(4, {st_mode=S_IFREG|0755, st_size=32080, ...}) = 0
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f39857db000
read(4, "#!/usr/bin/env python\nfrom __fut"..., 32256) = 32080
write(2, "    ", 4    )                     = 4
write(2, "main(sys.argv)\n", 15main(sys.argv)
)        = 15
close(4)                                = 0
munmap(0x7f39857db000, 32768)           = 0
write(2, "  File \"./vm.py\", line 928, in m"..., 36  File "./vm.py", line 928, in main
) = 36
open("./vm.py", O_RDONLY)               = 4
fstat(4, {st_mode=S_IFREG|0755, st_size=32080, ...}) = 0
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f39857db000
read(4, "#!/usr/bin/env python\nfrom __fut"..., 32256) = 32080
write(2, "    ", 4    )                     = 4
write(2, "do_fun(args[1:])\n", 17do_fun(args[1:])
)      = 17
close(4)                                = 0
munmap(0x7f39857db000, 32768)           = 0
write(2, "  File \"./vm.py\", line 543, in c"..., 40  File "./vm.py", line 543, in cmd_list
) = 40
open("./vm.py", O_RDONLY)               = 4
fstat(4, {st_mode=S_IFREG|0755, st_size=32080, ...}) = 0
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f39857db000
read(4, "#!/usr/bin/env python\nfrom __fut"..., 32256) = 32080
write(2, "    ", 4    )                     = 4
write(2, "filesystems = FS.list(None if le"..., 58filesystems = FS.list(None if len(args) < 1 else args[0])
) = 58
close(4)                                = 0
munmap(0x7f39857db000, 32768)           = 0
write(2, "  File \"./vm.py\", line 251, in l"..., 36  File "./vm.py", line 251, in list
) = 36
open("./vm.py", O_RDONLY)               = 4
fstat(4, {st_mode=S_IFREG|0755, st_size=32080, ...}) = 0
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f39857db000
read(4, "#!/usr/bin/env python\nfrom __fut"..., 32256) = 32080
write(2, "    ", 4    )                     = 4
write(2, "fs = filesystems[fsname]\n", 25fs = filesystems[fsname]
) = 25
close(4)                                = 0
munmap(0x7f39857db000, 32768)           = 0
write(2, "KeyError", 8KeyError)                 = 8
write(2, ": ", 2: )                       = 2
write(2, "'rpool/DATA/kvm/mail/data'", 26'rpool/DATA/kvm/mail/data') = 26
write(2, "\n", 1
)                       = 1
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f3985007a00}, {0x7f398531059b, [], SA_RESTORER, 0x7f3985007a00}, 8) = 0
brk(0x78e000)                           = 0x78e000
close(3)                                = 0
munmap(0x7f3985615000, 262144)          = 0
close(6)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
`
The list of them values, listing with zfs only have proper output:
`backup zfs-vm # zfs get -H -p -o name,property,value guid,createtxg rpool/DATA/kvm/mail/data
rpool/DATA/kvm/mail/data        guid    17624858773064996153
rpool/DATA/kvm/mail/data        createtxg       2360436`

What could be wrong, something with dataset name ?

**Comment by mkhon** [comment]
Can you provide the output of the following command:

zfs get -H -p -o name,property,value -t filesystem origin,mountpoint
